Download test result artifact

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -18,13 +18,30 @@ jobs:
     - name: Build
       run: dotnet build ./src
     - name: Test with the dotnet CLI
-      run: dotnet test ./src --logger:trx;LogFileName=test-results.trx;MethodFormat=Class;FailureBodyFormat=Verbose || true
-    - name: Test Report
-      uses: dorny/test-reporter@v1
+      run: dotnet test ./src/tests/**/*.csproj --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"
+    - name: Upload Test Results
       if: always()
+      uses: actions/upload-artifact@v2
+      with:
+        name: Test Results
+        path: "TestResults/test-results.trx"
+
+  test-results:
+    runs-on: ubuntu-latest
+    needs: build
+    if: success() || failure()
+
+    steps:
+    - name: Download Artifacts
+      uses: actions/download-artifact@v2
+      with:
+        path: artifacts
+    - name: Publish Unit Test Results
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
       with:
         name: Unit and Integration Tests
-        path: "src/tests/**/test-results.trx"
+        path: "TestResults/test-results.trx"
         reporter: dotnet-trx
         fail-on-error: true
 
